CREATE TABLE [Attendance] (
	ID int NOT NULL,
	UserID int NOT NULL,
	LessonID int NOT NULL,
	IsPresent bit NOT NULL,
  CONSTRAINT [PK_ATTENDANCE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)
)