CREATE TABLE [Course_Material] (
	ID int NOT NULL,
	CourseID int NOT NULL,
	MaterialID int NOT NULL,
  CONSTRAINT [PK_COURSE_MATERIAL] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)