CREATE TABLE [Feedback] (
	ID int NOT NULL,
	UserID int NOT NULL,
	LessonID int NOT NULL,
	Message nvarchar(1000) NOT NULL,
  CONSTRAINT [PK_FEEDBACK] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)