CREATE TABLE [Group_Material] (
	ID int NOT NULL,
	GroupID int NOT NULL,
	MaterialID int NOT NULL,
	  CONSTRAINT [PK_GROUP_MATERIAL] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)