CREATE TABLE [Homework_Course] (
	ID int NOT NULL,
	Homework int NOT NULL,
	CourseID int NOT NULL,
  CONSTRAINT [PK_HOMEWORK_COURSE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)