CREATE TABLE [Role_Privileges] (
	ID int NOT NULL,
	RoleID int NOT NULL,
	PrivilegesID int NOT NULL,
  CONSTRAINT [PK_ROLE_PRIVILEGES] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)