CREATE TABLE [Theme_Material] (
	ID int NOT NULL,
	ThemeID int NOT NULL,
	MaterialID int NOT NULL,
  CONSTRAINT [PK_THEME_MATERIAL] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)