CREATE TABLE [User_Role] 
(
	ID INT CONSTRAINT PK_User_Role PRIMARY KEY IDENTITY NOT NULL,
	UserID int NOT NULL,
	RoleID int NOT NULL,
  CONSTRAINT [FK_User_Role_User] FOREIGN KEY ([UserID]) REFERENCES [User]([ID]),
  CONSTRAINT [FK_User_Role_Role] FOREIGN KEY ([RoleID]) REFERENCES [Role]([ID])
)
