ALTER TABLE [User_Role] WITH CHECK ADD CONSTRAINT [User_Role_fk0] FOREIGN KEY ([UserID]) REFERENCES [User]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [User_Role] CHECK CONSTRAINT [User_Role_fk0]
GO
ALTER TABLE [User_Role] WITH CHECK ADD CONSTRAINT [User_Role_fk1] FOREIGN KEY ([RoleID]) REFERENCES [Role]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [User_Role] CHECK CONSTRAINT [User_Role_fk1]
GO

ALTER TABLE [Role_Privileges] WITH CHECK ADD CONSTRAINT [Role_Privileges_fk0] FOREIGN KEY ([RoleID]) REFERENCES [Role]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Role_Privileges] CHECK CONSTRAINT [Role_Privileges_fk0]
GO
ALTER TABLE [Role_Privileges] WITH CHECK ADD CONSTRAINT [Role_Privileges_fk1] FOREIGN KEY ([PrivilegesID]) REFERENCES [Privileges]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Role_Privileges] CHECK CONSTRAINT [Role_Privileges_fk1]
GO

ALTER TABLE [Attendance] WITH CHECK ADD CONSTRAINT [Attendance_fk0] FOREIGN KEY ([UserID]) REFERENCES [User]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Attendance] CHECK CONSTRAINT [Attendance_fk0]
GO
ALTER TABLE [Attendance] WITH CHECK ADD CONSTRAINT [Attendance_fk1] FOREIGN KEY ([LessonID]) REFERENCES [Lesson]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Attendance] CHECK CONSTRAINT [Attendance_fk1]
GO

ALTER TABLE [Feedback] WITH CHECK ADD CONSTRAINT [Feedback_fk0] FOREIGN KEY ([UserID]) REFERENCES [User]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Feedback] CHECK CONSTRAINT [Feedback_fk0]
GO
ALTER TABLE [Feedback] WITH CHECK ADD CONSTRAINT [Feedback_fk1] FOREIGN KEY ([LessonID]) REFERENCES [Lesson]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Feedback] CHECK CONSTRAINT [Feedback_fk1]
GO

ALTER TABLE [Lesson] WITH CHECK ADD CONSTRAINT [Lesson_fk0] FOREIGN KEY ([GroupID]) REFERENCES [Group]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Lesson] CHECK CONSTRAINT [Lesson_fk0]
GO

ALTER TABLE [User] WITH CHECK ADD CONSTRAINT [User_fk0] FOREIGN KEY ([StatusID]) REFERENCES [UserStatus]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [User] CHECK CONSTRAINT [User_fk0]
GO

ALTER TABLE [Group] WITH CHECK ADD CONSTRAINT [Group_fk0] FOREIGN KEY ([StatusID]) REFERENCES [GroupStatus]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Group] CHECK CONSTRAINT [Group_fk0]
GO
ALTER TABLE [Group] WITH CHECK ADD CONSTRAINT [Group_fk1] FOREIGN KEY ([CourseID]) REFERENCES [Course]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Group] CHECK CONSTRAINT [Group_fk1]
GO
ALTER TABLE [Group] WITH CHECK ADD CONSTRAINT [Group_fk2] FOREIGN KEY ([CityID]) REFERENCES [City]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Group] CHECK CONSTRAINT [Group_fk2]
GO

ALTER TABLE [Group_Material] WITH CHECK ADD CONSTRAINT [Group_Material_fk0] FOREIGN KEY ([GroupID]) REFERENCES [Group]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Group_Material] CHECK CONSTRAINT [Group_Material_fk0]
GO
ALTER TABLE [Group_Material] WITH CHECK ADD CONSTRAINT [Group_Material_fk1] FOREIGN KEY ([MaterialID]) REFERENCES [Material]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Group_Material] CHECK CONSTRAINT [Group_Material_fk1]
GO

ALTER TABLE [User_Group] WITH CHECK ADD CONSTRAINT [User_Group_fk0] FOREIGN KEY ([UserID]) REFERENCES [User]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [User_Group] CHECK CONSTRAINT [User_Group_fk0]
GO
ALTER TABLE [User_Group] WITH CHECK ADD CONSTRAINT [User_Group_fk1] FOREIGN KEY ([GroupID]) REFERENCES [Group]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [User_Group] CHECK CONSTRAINT [User_Group_fk1]
GO


ALTER TABLE [Group_Homework] WITH CHECK ADD CONSTRAINT [Group_Homework_fk0] FOREIGN KEY ([GroupID]) REFERENCES [Group]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Group_Homework] CHECK CONSTRAINT [Group_Homework_fk0]
GO
ALTER TABLE [Group_Homework] WITH CHECK ADD CONSTRAINT [Group_Homework_fk1] FOREIGN KEY ([HomeworkID]) REFERENCES [Homework]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Group_Homework] CHECK CONSTRAINT [Group_Homework_fk1]
GO

ALTER TABLE [Lesson_Theme] WITH CHECK ADD CONSTRAINT [Lesson_Theme_fk0] FOREIGN KEY ([LessonID]) REFERENCES [Lesson]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Lesson_Theme] CHECK CONSTRAINT [Lesson_Theme_fk0]
GO
ALTER TABLE [Lesson_Theme] WITH CHECK ADD CONSTRAINT [Lesson_Theme_fk1] FOREIGN KEY ([ThemeID]) REFERENCES [Theme]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Lesson_Theme] CHECK CONSTRAINT [Lesson_Theme_fk1]
GO

ALTER TABLE [Payment] WITH CHECK ADD CONSTRAINT [Payment_fk0] FOREIGN KEY ([UserID]) REFERENCES [User]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Payment] CHECK CONSTRAINT [Payment_fk0]
GO
ALTER TABLE [Payment] WITH CHECK ADD CONSTRAINT [Payment_fk1] FOREIGN KEY ([GroupID]) REFERENCES [Group]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Payment] CHECK CONSTRAINT [Payment_fk1]
GO

ALTER TABLE [Material] WITH CHECK ADD CONSTRAINT [Material_fk0] FOREIGN KEY ([UserID]) REFERENCES [User]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Material] CHECK CONSTRAINT [Material_fk0]
GO
ALTER TABLE [Material] WITH CHECK ADD CONSTRAINT [Material_fk1] FOREIGN KEY ([ResourceID]) REFERENCES [Resource]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Material] CHECK CONSTRAINT [Material_fk1]
GO

ALTER TABLE [Comment] WITH CHECK ADD CONSTRAINT [Comment_fk0] FOREIGN KEY ([UserID]) REFERENCES [User]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Comment] CHECK CONSTRAINT [Comment_fk0]
GO
ALTER TABLE [Comment] WITH CHECK ADD CONSTRAINT [Comment_fk1] FOREIGN KEY ([AnswerID]) REFERENCES [Answer]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Comment] CHECK CONSTRAINT [Comment_fk1]
GO
ALTER TABLE [Comment] WITH CHECK ADD CONSTRAINT [Comment_fk2] FOREIGN KEY ([ResourceID]) REFERENCES [Resource]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Comment] CHECK CONSTRAINT [Comment_fk2]
GO



ALTER TABLE [Course_Theme] WITH CHECK ADD CONSTRAINT [Course_Theme_fk0] FOREIGN KEY ([CourseId]) REFERENCES [Course]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Course_Theme] CHECK CONSTRAINT [Course_Theme_fk0]
GO
ALTER TABLE [Course_Theme] WITH CHECK ADD CONSTRAINT [Course_Theme_fk1] FOREIGN KEY ([ThemeID]) REFERENCES [Theme]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Course_Theme] CHECK CONSTRAINT [Course_Theme_fk1]
GO

ALTER TABLE [Course_Material] WITH CHECK ADD CONSTRAINT [Course_Material_fk0] FOREIGN KEY ([CourseID]) REFERENCES [Course]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Course_Material] CHECK CONSTRAINT [Course_Material_fk0]
GO
ALTER TABLE [Course_Material] WITH CHECK ADD CONSTRAINT [Course_Material_fk1] FOREIGN KEY ([MaterialID]) REFERENCES [Material]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Course_Material] CHECK CONSTRAINT [Course_Material_fk1]
GO

ALTER TABLE [Theme_Tag] WITH CHECK ADD CONSTRAINT [Theme_Tag_fk0] FOREIGN KEY ([ThemeID]) REFERENCES [Theme]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Theme_Tag] CHECK CONSTRAINT [Theme_Tag_fk0]
GO
ALTER TABLE [Theme_Tag] WITH CHECK ADD CONSTRAINT [Theme_Tag_fk1] FOREIGN KEY ([TagID]) REFERENCES [Tag]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Theme_Tag] CHECK CONSTRAINT [Theme_Tag_fk1]
GO


ALTER TABLE [Material_Tag] WITH CHECK ADD CONSTRAINT [Material_Tag_fk0] FOREIGN KEY ([MaterialID]) REFERENCES [Material]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Material_Tag] CHECK CONSTRAINT [Material_Tag_fk0]
GO
ALTER TABLE [Material_Tag] WITH CHECK ADD CONSTRAINT [Material_Tag_fk1] FOREIGN KEY ([TagID]) REFERENCES [Tag]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Material_Tag] CHECK CONSTRAINT [Material_Tag_fk1]
GO


ALTER TABLE [Homework_Tag] WITH CHECK ADD CONSTRAINT [Homework_Tag_fk0] FOREIGN KEY ([HomeworkID]) REFERENCES [Homework]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Homework_Tag] CHECK CONSTRAINT [Homework_Tag_fk0]
GO
ALTER TABLE [Homework_Tag] WITH CHECK ADD CONSTRAINT [Homework_Tag_fk1] FOREIGN KEY ([TagID]) REFERENCES [Tag]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Homework_Tag] CHECK CONSTRAINT [Homework_Tag_fk1]
GO



ALTER TABLE [Answer] WITH CHECK ADD CONSTRAINT [Answer_fk1] FOREIGN KEY ([HomeWorkID]) REFERENCES [Homework]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Answer] CHECK CONSTRAINT [Answer_fk1]
GO
ALTER TABLE [Answer] WITH CHECK ADD CONSTRAINT [Answer_fk2] FOREIGN KEY ([StatusID]) REFERENCES [Answer_Status]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Answer] CHECK CONSTRAINT [Answer_fk2]
GO
ALTER TABLE [Answer] WITH CHECK ADD CONSTRAINT [Answer_fk0] FOREIGN KEY ([UserID]) REFERENCES [User]([ID])

GO
ALTER TABLE [Answer] CHECK CONSTRAINT [Answer_fk0]
GO


ALTER TABLE [Theme_Material] WITH CHECK ADD CONSTRAINT [Theme_Material_fk0] FOREIGN KEY ([ThemeID]) REFERENCES [Theme]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Theme_Material] CHECK CONSTRAINT [Theme_Material_fk0]
GO
ALTER TABLE [Theme_Material] WITH CHECK ADD CONSTRAINT [Theme_Material_fk1] FOREIGN KEY ([MaterialID]) REFERENCES [Material]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Theme_Material] CHECK CONSTRAINT [Theme_Material_fk1]
GO

GO
ALTER TABLE [Homework] WITH CHECK ADD CONSTRAINT [Homework_fk0] FOREIGN KEY ([ResourceID]) REFERENCES [Resource]([ID])
GO

ALTER TABLE [Homework_Theme] WITH CHECK ADD CONSTRAINT [Homework_Theme_fk0] FOREIGN KEY ([HomeworkD]) REFERENCES [Homework]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Homework_Theme] CHECK CONSTRAINT [Homework_Theme_fk0]
GO
ALTER TABLE [Homework_Theme] WITH CHECK ADD CONSTRAINT [Homework_Theme_fk1] FOREIGN KEY ([ThemeID]) REFERENCES [Theme]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Homework_Theme] CHECK CONSTRAINT [Homework_Theme_fk1]
GO

ALTER TABLE [Homework_Course] WITH CHECK ADD CONSTRAINT [Homework_Course_fk0] FOREIGN KEY ([Homework]) REFERENCES [Homework]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Homework_Course] CHECK CONSTRAINT [Homework_Course_fk0]
GO
ALTER TABLE [Homework_Course] WITH CHECK ADD CONSTRAINT [Homework_Course_fk1] FOREIGN KEY ([CourseID]) REFERENCES [Course]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Homework_Course] CHECK CONSTRAINT [Homework_Course_fk1]
GO